# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd7a26e874bb2a286ff7c36d6c25443eb0493641d1c379e5149aa3dc6a983f7a4b29cec5b5f4c9bf379e65ffa5b0686c43b1e2473adc1b44dbb0e1eb160e023d

test:
  secret_key_base: d6cfa22422b899e1fbb0cbdaed2373da4c64d42d0d1b7abe7b1f0c8277782c1fe9a90979284795284536bfdf2d9c135a1a0f4384aeb1667395cb864e8cf780a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
